apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-alerts
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:                 # <--- IL MANQUAIT CETTE LIGNE
  groups:             # <--- 'groups' doit être décalé (indenté) sous 'spec'
  - name: flask.rules
    rules:
    - alert: FlaskServiceMissing
      expr: absent(up{service="flask-service"}) == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "L'application Flask a disparu"
        description: "Le déploiement a été supprimé ou le service est introuvable."