apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-alerts
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
groups:
- name: flask.rules
  rules:
  - alert: FlaskServiceMissing
    # "Si la métrique up pour l'app flask n'existe plus"
    expr: absent(up{app="flask"}) == 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "L'application Flask a disparu"
      description: "Le déploiement a été supprimé ou le service est introuvable."